/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
[2024-11-16 03:00:37,289: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-11-16 03:00:37,430: INFO/MainProcess] data3-node@ph ready.
[2024-11-16 03:05:15,559: INFO/MainProcess] Received task: data.tasks.import_cve_task[0799056f-6eb9-44dd-af5c-ba6d46295dde]  
[2024-11-16 03:05:15,569: INFO/MainProcess] Received task: data.tasks.import_cve_task[6e276a77-410f-4418-aa03-21eae45779f1]  
[2024-11-16 03:05:15,585: INFO/MainProcess] Received task: data.tasks.import_cve_task[3f00061f-b89e-4435-aa57-ed7c13396f66]  
[2024-11-16 03:05:15,597: INFO/MainProcess] Received task: data.tasks.import_cve_task[6011fc07-7fdd-4245-ba52-658de531cb69]  
[2024-11-16 03:05:16,286: INFO/ForkPoolWorker-7] Task data.tasks.import_cve_task[0799056f-6eb9-44dd-af5c-ba6d46295dde] succeeded in 0.6870886560063809s: None
[2024-11-16 03:05:16,299: INFO/ForkPoolWorker-1] Task data.tasks.import_cve_task[3f00061f-b89e-4435-aa57-ed7c13396f66] succeeded in 0.691910227003973s: None
[2024-11-16 03:05:16,456: INFO/ForkPoolWorker-8] Task data.tasks.import_cve_task[6e276a77-410f-4418-aa03-21eae45779f1] succeeded in 0.8528634220128879s: None
[2024-11-16 03:05:16,543: INFO/ForkPoolWorker-9] Task data.tasks.import_cve_task[6011fc07-7fdd-4245-ba52-658de531cb69] succeeded in 0.8436710450332612s: None
[2024-11-16 17:31:33,202: INFO/MainProcess] Received task: data.tasks.import_cve_task[49e2aab7-86ca-4570-a145-92072c51bf0a]  
[2024-11-16 17:31:33,231: INFO/MainProcess] Received task: data.tasks.import_cve_task[19416114-4db8-4642-86a9-c21e6a12ccf3]  
[2024-11-16 17:31:33,232: INFO/MainProcess] Received task: data.tasks.import_cve_task[3c0f8fdc-d784-446d-87e5-42f2b3096ed3]  
[2024-11-16 17:31:33,272: INFO/MainProcess] Received task: data.tasks.import_cve_task[7a4b1e4e-92a4-4291-83c1-53176af8e750]  
[2024-11-16 17:31:33,273: INFO/MainProcess] Received task: data.tasks.import_cve_task[62f0060a-4d7a-41c7-9f71-193c7c0bce51]  
[2024-11-16 17:31:33,282: INFO/MainProcess] Received task: data.tasks.import_cve_task[941b5066-aa1e-4597-9671-6bbb48723d18]  
[2024-11-16 17:31:35,138: INFO/ForkPoolWorker-7] Task data.tasks.import_cve_task[49e2aab7-86ca-4570-a145-92072c51bf0a] succeeded in 1.6955476949806325s: None
[2024-11-16 17:31:35,410: INFO/ForkPoolWorker-9] Task data.tasks.import_cve_task[7a4b1e4e-92a4-4291-83c1-53176af8e750] succeeded in 1.8607417379971594s: None
[2024-11-16 17:31:35,589: INFO/ForkPoolWorker-1] Task data.tasks.import_cve_task[3c0f8fdc-d784-446d-87e5-42f2b3096ed3] succeeded in 2.1422724059666507s: None
[2024-11-16 17:31:35,658: INFO/ForkPoolWorker-8] Task data.tasks.import_cve_task[19416114-4db8-4642-86a9-c21e6a12ccf3] succeeded in 2.356397399038542s: None
[2024-11-16 17:31:36,540: INFO/ForkPoolWorker-2] Task data.tasks.import_cve_task[62f0060a-4d7a-41c7-9f71-193c7c0bce51] succeeded in 3.1061013090074994s: None
[2024-11-16 17:31:36,591: INFO/ForkPoolWorker-10] Task data.tasks.import_cve_task[941b5066-aa1e-4597-9671-6bbb48723d18] succeeded in 2.997212184011005s: None

worker: Warm shutdown (MainProcess)
/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
[2024-11-18 17:16:00,893: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-11-18 17:16:01,016: INFO/MainProcess] data3-node@ph ready.
[2024-11-18 21:11:57,900: INFO/MainProcess] Received task: data.tasks.import_cve_task[69ac5a82-41d4-4ccb-b80e-80f1e265906f]  
[2024-11-18 21:11:58,000: INFO/MainProcess] Received task: data.tasks.import_cve_task[178e8dc1-79fb-465d-ae4e-d76667fecc85]  
[2024-11-18 21:11:58,004: INFO/MainProcess] Received task: data.tasks.import_cve_task[876bc670-8194-4d61-a31a-f9624ff02cb2]  
[2024-11-18 21:11:58,048: INFO/MainProcess] Received task: data.tasks.import_cve_task[54da76c8-9326-449f-996c-64f5e27e1199]  
[2024-11-18 21:11:58,048: INFO/MainProcess] Received task: data.tasks.import_cve_task[d12923d2-22aa-4cdd-a5e6-de27f06b6ba8]  
[2024-11-18 21:11:58,049: INFO/MainProcess] Received task: data.tasks.import_cve_task[c4e15d6a-55f2-4628-9ed1-20ad578dccda]  
[2024-11-18 21:11:58,078: INFO/MainProcess] Received task: data.tasks.import_cve_task[339bb568-93a6-407e-8df2-941819d24703]  
[2024-11-18 21:11:58,079: INFO/MainProcess] Received task: data.tasks.import_cve_task[ddda69ac-f3be-462c-a444-e25eac952e62]  
[2024-11-18 21:11:58,122: INFO/MainProcess] Received task: data.tasks.import_cve_task[9d048da1-4c3a-4af6-946e-8e00810b5d86]  
[2024-11-18 21:11:58,123: INFO/MainProcess] Received task: data.tasks.import_cve_task[efdf4429-dcdc-437c-b6bf-536a309667d5]  
[2024-11-18 21:11:58,201: INFO/MainProcess] Received task: data.tasks.import_cve_task[2e62a8fc-5994-4430-8196-0d9fef0d45a5]  
[2024-11-18 21:11:59,937: INFO/ForkPoolWorker-5] Task data.tasks.import_cve_task[9d048da1-4c3a-4af6-946e-8e00810b5d86] succeeded in 1.7931853689951822s: None
[2024-11-18 21:11:59,966: INFO/ForkPoolWorker-3] Task data.tasks.import_cve_task[339bb568-93a6-407e-8df2-941819d24703] succeeded in 1.8330452759983018s: None
[2024-11-18 21:12:00,094: INFO/ForkPoolWorker-10] Task data.tasks.import_cve_task[c4e15d6a-55f2-4628-9ed1-20ad578dccda] succeeded in 1.9613047019811347s: None
[2024-11-18 21:12:00,113: INFO/ForkPoolWorker-2] Task data.tasks.import_cve_task[d12923d2-22aa-4cdd-a5e6-de27f06b6ba8] succeeded in 1.9867624300532043s: None
[2024-11-18 21:12:00,260: INFO/ForkPoolWorker-9] Task data.tasks.import_cve_task[54da76c8-9326-449f-996c-64f5e27e1199] succeeded in 2.1341318269260228s: None
[2024-11-18 21:12:00,290: INFO/ForkPoolWorker-4] Task data.tasks.import_cve_task[ddda69ac-f3be-462c-a444-e25eac952e62] succeeded in 2.1500065829604864s: None
[2024-11-18 21:12:00,299: INFO/ForkPoolWorker-6] Task data.tasks.import_cve_task[efdf4429-dcdc-437c-b6bf-536a309667d5] succeeded in 2.1581479189917445s: None
[2024-11-18 21:12:00,299: INFO/ForkPoolWorker-1] Task data.tasks.import_cve_task[876bc670-8194-4d61-a31a-f9624ff02cb2] succeeded in 2.258652967051603s: None
[2024-11-18 21:12:00,353: INFO/ForkPoolWorker-7] Task data.tasks.import_cve_task[69ac5a82-41d4-4ccb-b80e-80f1e265906f] succeeded in 2.3188441019738093s: None
[2024-11-18 21:12:00,414: INFO/ForkPoolWorker-8] Task data.tasks.import_cve_task[178e8dc1-79fb-465d-ae4e-d76667fecc85] succeeded in 2.377813001978211s: None
[2024-11-18 21:12:00,440: INFO/ForkPoolWorker-5] Task data.tasks.import_cve_task[2e62a8fc-5994-4430-8196-0d9fef0d45a5] succeeded in 0.45506719092372805s: None
[2024-11-18 21:12:00,750: INFO/MainProcess] Received task: data.tasks.import_cve_task[4fcf9596-f6e1-4f9f-9f79-5d1dc63107b8]  
[2024-11-18 21:12:00,774: INFO/MainProcess] Received task: data.tasks.import_cve_task[62d357df-507f-4688-830c-3e8390e1a10b]  
[2024-11-18 21:12:00,810: INFO/MainProcess] Received task: data.tasks.import_cve_task[f0863c0a-938e-479e-88a5-a46b93b24d5a]  
[2024-11-18 21:12:00,896: INFO/MainProcess] Received task: data.tasks.import_cve_task[aaf78c9c-2970-47a6-b52c-19d6b2853797]  
[2024-11-18 21:12:00,970: INFO/MainProcess] Received task: data.tasks.import_cve_task[579def3c-1d65-4abb-b702-07acc0c2b14c]  
[2024-11-18 21:12:01,051: INFO/MainProcess] Received task: data.tasks.import_cve_task[f81d5577-bca3-48c1-a14b-8535bf5a3658]  
[2024-11-18 21:12:01,072: INFO/ForkPoolWorker-7] Task data.tasks.import_cve_task[4fcf9596-f6e1-4f9f-9f79-5d1dc63107b8] succeeded in 0.32091781101189554s: None
[2024-11-18 21:12:01,231: INFO/ForkPoolWorker-8] Task data.tasks.import_cve_task[62d357df-507f-4688-830c-3e8390e1a10b] succeeded in 0.4515755570027977s: None
[2024-11-18 21:12:01,283: INFO/ForkPoolWorker-1] Task data.tasks.import_cve_task[f0863c0a-938e-479e-88a5-a46b93b24d5a] succeeded in 0.4666589580010623s: None
[2024-11-18 21:12:01,287: INFO/ForkPoolWorker-9] Task data.tasks.import_cve_task[aaf78c9c-2970-47a6-b52c-19d6b2853797] succeeded in 0.390039868070744s: None
[2024-11-18 21:12:01,381: INFO/ForkPoolWorker-10] Task data.tasks.import_cve_task[f81d5577-bca3-48c1-a14b-8535bf5a3658] succeeded in 0.32848558702971786s: None
[2024-11-18 21:12:01,395: INFO/ForkPoolWorker-2] Task data.tasks.import_cve_task[579def3c-1d65-4abb-b702-07acc0c2b14c] succeeded in 0.4240192750003189s: None
[2024-11-19 04:27:30,010: INFO/MainProcess] Received task: data.tasks.import_cve_task[8ac5098b-f7c4-4841-a3b0-614d7bcab606]  
[2024-11-19 04:27:30,021: INFO/MainProcess] Received task: data.tasks.import_cve_task[769489da-99f6-411d-b865-2187bf74c867]  
[2024-11-19 04:27:30,028: INFO/MainProcess] Received task: data.tasks.import_cve_task[ea74cb29-fef7-4293-83c7-702ae8483a02]  
[2024-11-19 04:27:30,050: INFO/MainProcess] Received task: data.tasks.import_cve_task[55f88c99-3b22-4f4a-888a-9410154f1cfd]  
[2024-11-19 04:27:30,051: INFO/MainProcess] Received task: data.tasks.import_cve_task[d73b4fc4-d16d-47c6-9d3b-8defb8f49db5]  
[2024-11-19 04:27:30,847: INFO/ForkPoolWorker-7] Task data.tasks.import_cve_task[8ac5098b-f7c4-4841-a3b0-614d7bcab606] succeeded in 0.8014310059370473s: None
[2024-11-19 04:27:30,860: INFO/ForkPoolWorker-8] Task data.tasks.import_cve_task[769489da-99f6-411d-b865-2187bf74c867] succeeded in 0.7933946060948074s: None
[2024-11-19 04:27:30,935: INFO/ForkPoolWorker-9] Task data.tasks.import_cve_task[55f88c99-3b22-4f4a-888a-9410154f1cfd] succeeded in 0.8502960470505059s: None
[2024-11-19 04:27:30,946: INFO/ForkPoolWorker-2] Task data.tasks.import_cve_task[d73b4fc4-d16d-47c6-9d3b-8defb8f49db5] succeeded in 0.8464163090102375s: None
[2024-11-19 04:27:30,956: INFO/ForkPoolWorker-1] Task data.tasks.import_cve_task[ea74cb29-fef7-4293-83c7-702ae8483a02] succeeded in 0.8942346420371905s: None
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.20/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/worker/worker.py", line 96, in __init__
    self.app.loader.init_worker()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.9.20/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/PatrowlHears/backend_app/users/models.py", line 6, in <module>
    from vulns.models import Vuln
  File "/root/PatrowlHears/backend_app/vulns/models.py", line 8, in <module>
    from alerts.models import AlertingRule
  File "/root/PatrowlHears/backend_app/alerts/models.py", line 6, in <module>
    from .tasks import send_email_message_task
  File "/root/PatrowlHears/backend_app/alerts/tasks.py", line 4, in <module>
    from backend_app import slack, telegram, escape_markdown
ImportError: cannot import name 'escape_markdown' from 'backend_app' (/root/PatrowlHears/backend_app/backend_app/__init__.py)
/root/.pyenv/versions/3.9.20/lib/python3.9/site-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
[2024-11-19 09:58:27,338: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2024-11-19 09:58:27,377: INFO/MainProcess] data3-node@ph ready.
[2024-11-20 03:25:08,255: INFO/MainProcess] Received task: data.tasks.import_cve_task[e00cb101-1d6c-44c4-9b63-8c12c7e16d5c]  
[2024-11-20 03:25:08,272: INFO/MainProcess] Received task: data.tasks.import_cve_task[fe463483-efa7-444b-88e4-9a89c7d54487]  
[2024-11-20 03:25:08,273: INFO/MainProcess] Received task: data.tasks.import_cve_task[d2161b4d-ed5a-4d58-a3e8-f7856287ea3d]  
[2024-11-20 03:25:09,275: INFO/ForkPoolWorker-8] Task data.tasks.import_cve_task[fe463483-efa7-444b-88e4-9a89c7d54487] succeeded in 0.9830440569930943s: None
[2024-11-20 03:25:09,494: INFO/ForkPoolWorker-7] Task data.tasks.import_cve_task[e00cb101-1d6c-44c4-9b63-8c12c7e16d5c] succeeded in 1.198203106992878s: None
[2024-11-20 03:25:09,558: INFO/ForkPoolWorker-1] Task data.tasks.import_cve_task[d2161b4d-ed5a-4d58-a3e8-f7856287ea3d] succeeded in 1.270242678001523s: None
